float:
  euclidean:
  - base_args: ['@metric']
    constructor: TileDBIVFFlat
    disabled: false
    docker_tag: ann-benchmarks-tiledb
    module: ann_benchmarks.algorithms.tiledb
    name: tiledb-ivf-flat
    run_groups:
      base:
        args: [[512, 1024, 2048, 4096, 8192]]
        query_args: [[1, 5, 10, 50, 100, 200]]
