float:
  euclidean:
  - base_args: ['@metric']
    constructor: TileDBIVFFlat
    disabled: false
    docker_tag: ann-benchmarks-tiledb
    module: ann_benchmarks.algorithms.tiledb
    name: tiledb-ivf-flat
    run_groups:
      IVFFLAT:
        # n_list:
        args: [[512, 1024, 2048, 4096, 8192]]
        # n_probe:
        query_args: [[1, 5, 10, 50, 100, 200]]

  - base_args: ['@metric']
    constructor: TileDBFlat
    disabled: false
    docker_tag: ann-benchmarks-tiledb
    module: ann_benchmarks.algorithms.tiledb
    name: tiledb-flat
    run_groups:
      FLAT:
        args:
            placeholder: [0]

  - base_args: ['@metric']
    constructor: TileDBVamana
    disabled: false
    docker_tag: ann-benchmarks-tiledb
    module: ann_benchmarks.algorithms.tiledb
    name: tiledb-vamana
    run_groups:
      VAMANA:
        # r_max_degree:
        args: [[10, 15, 20, 25, 30, 35, 40]]
        # l_search:
        query_args: [[1, 5, 10, 30, 50, 70, 90, 110, 130]]

  - base_args: ['@metric']
    constructor: TileDBIVFPQ
    disabled: false
    docker_tag: ann-benchmarks-tiledb
    module: ann_benchmarks.algorithms.tiledb
    name: tiledb-ivf-pq
    run_groups:
      IVFPQ:
        args: [
          # n_list:
          [512, 1024, 2048, 4096, 8192],
          # num_subspaces divisor:
          [1, 2, 4, 8]
        ]
        # n_probe:
        query_args: [[1, 5, 10, 50, 100, 200]]
